# Generated by Django 5.0.2 on 2024-03-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_thumbnail',
            field=models.ImageField(blank=True, upload_to='post_images/', verbose_name='Мініатюра'),
        ),
    ]
